import type { Metadata } from "next";
import "./globals.css";
import LayoutProvider from "@/components/layoutProvider";
import React from "react";
import '@ant-design/v5-patch-for-react-19';




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LayoutProvider>
        {children}
    </LayoutProvider>
  );
}
